[package]
name = "cargo-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guessing-game"
path = "src/guessing-game/main.rs"

[dependencies]
rand = "0.8.3"
